# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "shanghai"
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.25"
  src = "src"
  test = "test"
  allow_paths = ["node_modules"]
  libs = ["/Users/ammar.robb/Documents/Web 3/Espresso/intents-framework/node_modules", "node_modules", "lib"]

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  arbitrum = { key = "${API_KEY_ARBISCAN}" }
  arbitrum-sepolia = { key = "${API_KEY_ARBISCAN}" }
  gtxpresso = { key = "" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  multiline_func_call = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  default_network = "http://127.0.0.1:8545"
  mainnet = "https://rpc.ankr.com/eth"
  arbitrum-sepolia = "https://arb-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  sepolia = "https://eth-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  gtxpresso = "http://157.173.201.26:8547"
