# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x1bfd9867a9B6e89CAAc8e258405F0a484486C8A3"
    chainName: arbitrumsepolia
    connections:
      - token: ethereum|gtxpresso|0xfecE754eFCAC66336a80E44F882D1521E54062A1
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0xfecE754eFCAC66336a80E44F882D1521E54062A1"
    chainName: gtxpresso
    connections:
      - token: ethereum|arbitrumsepolia|0x1bfd9867a9B6e89CAAc8e258405F0a484486C8A3
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
